export const transform = {
  fullMinus: "translate(-100%, -100%)",
  fullPlus: "translate(100%, 100%)",
  halfMinus: "translate(-50%, -50%)",
  halfPlus: "translate(50%, 50%)",
  none: "translate(0, 0)",
  xFullMinus: "translateX(-100%)",
  xFullPlus: "translateX(100%)",
  xHalfMinus: "translateX(-50%)",
  xHalfPlus: "translateX(50%)",
  xNone: "translateX(0)",
  yFullMinus: "translateY(-100%)",
  yFullPlus: "translateY(100%)",
  yHalfMinus: "translateY(-50%)",
  yHalfPlus: "translateY(50%)",
  yNone: "translateY(0)",
};
